name: Node.js CI

on:
  push:
    branches: master
  pull_request:

jobs:
  shellcheck:
    - run: ./scripts/scriptcheck ./scripts
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    # See: https://github.com/actions/setup-node/issues/480
    - run: corepack enable
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: |
          yarn.lock
    - run: yarn install --immutable
    - run: yarn test
